name: try running docker-compose then test.

on:
  workflow_dispatch: # Allow to run this workflow manually from the Actions tab

jobs:
  test-flask:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: run docker-compose
      run: docker-compose up -d

    - name: make sure that docker-compose is running & Install dependencies
      run: |
        docker ps
        pip install -r requirements.txt

    - name: run python tests
      run: python ./tests/test_hello.py